# Generated by Django 4.1.1 on 2022-11-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='file_manager.attachment')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
