# Generated by Django 4.1.1 on 2023-01-01 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permission_file', models.CharField(max_length=35)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('0', 'Mini Truck'), ('1', 'Truck'), ('2', 'Heavy Truck')], max_length=1)),
                ('container_type', models.CharField(choices=[('0', 'Open Air'), ('1', 'Regular'), ('2', 'Fridge')], max_length=1)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
