# Generated by Django 4.1.1 on 2022-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='permission',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
