# Generated by Django 4.1.1 on 2022-11-20 10:57

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_manager', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Phone', 'Phone'), ('E-Mail', 'Email')], default='Phone', max_length=10)),
                ('receiver', models.CharField(max_length=50)),
                ('code', models.CharField(default=users.models._generate_otp, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('type', models.CharField(choices=[('0', 'Unknown'), ('1', 'Individual Person'), ('2', 'Legal Person')], default='0', max_length=1)),
                ('role', models.CharField(choices=[('0', 'Unknows'), ('1', 'Trader'), ('2', 'Freight'), ('3', 'Producer')], default='0', max_length=1)),
                ('company_name', models.CharField(max_length=50)),
                ('company_origin', models.CharField(choices=[('0', 'Iranian'), ('1', 'Foreign')], default='0', max_length=50)),
                ('company_id', models.CharField(max_length=10, null=True)),
                ('company_national_id', models.CharField(max_length=10, null=True)),
                ('company_phone', models.CharField(max_length=11, null=True, unique=True)),
                ('company_fax', models.CharField(max_length=11, null=True)),
                ('url', models.URLField()),
                ('company_address', models.TextField()),
                ('ceo_name', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_phone', models.CharField(max_length=11, null=True, unique=True)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('company_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_doc', to='file_manager.attachment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='file_manager.attachment')),
                ('performa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa', to='file_manager.attachment')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
