# Generated by Django 4.1.1 on 2022-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_doc',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
