# Generated by Django 4.1.1 on 2022-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company_doc_alter_user_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
