# Generated by Django 4.1.1 on 2022-12-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_performa_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='password',
        ),
    ]
