# Generated by Django 4.1.1 on 2022-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_code_otp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
