# Generated by Django 4.1.1 on 2022-11-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('file_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('original_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.attachmenttemplate')),
            ],
        ),
    ]
