# Generated by Django 4.1.1 on 2022-12-18 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('orderer_acception', models.BooleanField(default=False)),
                ('freight_acception', models.BooleanField(default=False)),
                ('prepayment_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('order_number', models.CharField(blank=True, max_length=35, null=True)),
                ('order_number_file', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('0', 'FCA'), ('1', 'CPT')], max_length=1)),
                ('ordering_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=35, null=True)),
                ('order_number_file', models.CharField(blank=True, max_length=35, null=True)),
                ('product', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('vehicle_type', models.CharField(max_length=200)),
                ('loading_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('second_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('loading_date', models.DateTimeField()),
                ('border_passage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('proforma_file', models.CharField(max_length=35)),
                ('orderer_completion_date', models.DateTimeField(blank=True, null=True)),
                ('freight_completion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['loading_date'],
            },
        ),
        migrations.CreateModel(
            name='PaperWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_file', models.CharField(max_length=35)),
                ('upload_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('rejection_reasons', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_file', models.CharField(blank=True, max_length=35, null=True)),
                ('receipt_file', models.CharField(blank=True, max_length=35, null=True)),
                ('price', models.FloatField()),
                ('payment_date', models.DateField()),
                ('bill_status', models.BooleanField(default=False)),
                ('bill_rejection_reasons', models.TextField(blank=True)),
                ('receipt_status', models.BooleanField(default=False)),
                ('receipt_rejection_reasons', models.TextField(blank=True)),
            ],
        ),
    ]
