# Generated by Django 4.1.1 on 2022-12-18 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petro_seller_co', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='bijak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bijak', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='deal_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescript', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='demurrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demurrage_price', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='drivers_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers_info', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='final_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_payment', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='freight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_price', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_packing', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='lading_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lading_bill', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='load_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='load_info', to='orders.paperwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='offer',
            name='prepayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prepayment_receipt', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='second_destination_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_destination_cost', to='orders.payment'),
        ),
    ]
