# Generated by Django 4.1.1 on 2022-12-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['loading_date']},
        ),
    ]
