# Generated by Django 4.1.1 on 2022-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rejection_reasons',
            new_name='bill_rejection_reasons',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='bill_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_rejection_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_status',
            field=models.BooleanField(default=False),
        ),
    ]
