# Generated by Django 4.1.1 on 2022-12-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_rejection_reasons_payment_bill_rejection_reasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer_order_number', to='orders.paperwork'),
        ),
    ]
